### ISSUE TITLE
get_scratch! on read-only filesystem

### ISSUE THREAD

**Issue by olivierlabayle** [JuliaPackaging/Scratch.jl#33] opened 2022-10-21 10:48 UTC
Hi,

I am currently trying to use a singularity container that has TimeZones.jl and thus Scratch.jl as a dependency. The initialization of TimeZones.jl seems to call `get_scratch!` which tries to write a `manifest_usage.toml` file at run time. Unfortunately, singularity containers are read-only and thus I can't even load the original module.

Could you please provide some guidance on how I could fix this issue? Also please let me know if this issue should instead be opened on TimeZones.jl.

Thanks

**Comment by giordano** [comment] 2022-10-21 10:50
Sounds like a duplicate of #32: the first depot is always assumed to be writable.

**Closed** 2023-02-14 23:06 UTC
